name: Pipeline CI/CD

on:
  push:
    branches:
      - creacion-yml-ci-cd

permissions:
  pull-requests: read
jobs:
  SAST:
    runs-on: ubuntu-latest

    steps:
      - name: Analisis SonarCloud

        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=matias-avila_laboratorio-final
            -Dsonar.organization=matias-avila
          projectBaseDir: .
      - name: Validar Quality Gate
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        with:
          args:
            -Dsonar.qualitygate.wait=true
            -Dsonar.projectKey=matias-avila_laboratorio-final
            -Dsonar.organization=matias-avila
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SCA:
    needs: SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'matias-avila_laboratorio-final'
          path: './'
          format: 'HTML,JSON'
          out: 'dependency-check-report'
        continue-on-error: false