name: Pipeline CI/CD

on:
  push:
    branches:
      - creacion-yml-ci-cd

permissions:
  pull-requests: read
jobs:

  SAST:
    runs-on: ubuntu-latest

    steps:
      - name: Analisis SonarCloud

        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=matias-avila_laboratorio-final
            -Dsonar.organization=matias-avila
          projectBaseDir: .
      - name: Validar Quality Gate
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        with:
          args:
            -Dsonar.qualitygate.wait=true
            -Dsonar.projectKey=matias-avila_laboratorio-final
            -Dsonar.organization=matias-avila
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  SCA:
    needs: SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'matias-avila_laboratorio-final'
          path: './'
          format: 'ALL'
          out: 'dependency-check-report'
          args: '--failOnCVSS 4.0'
        continue-on-error: false #Cambiar a true para no detener el pipeline

  Docker:
    needs: [SAST, SCA]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir imagen Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/laboratorio-final:prueba .

      - name: Publicar imagen en DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/laboratorio-final:prueba

  ImageSecurity:
    needs: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Escanear imagen Docker con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/laboratorio-final:prueba'
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '1' #Cambiar a 0 para no detener el pipeline

  # SSH-Test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Probar conexión SSH
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.DOCKER_HOST }}
  #         username: ${{ secrets.DOCKER_USER }}
  #         key: ${{ secrets.DOCKER_SSH_KEY }}
  #         script: |
  #           echo "Conexión SSH exitosa a $HOSTNAME"

  Despliegue:
    needs: ImageSecurity
    runs-on: ubuntu-latest

    steps:
      - name: Desplegar Docker remoto por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_USER }}
          key: ${{ secrets.DOCKER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/laboratorio-final:prueba

            docker stop laboratorio-final || true
            docker rm laboratorio-final || true

            docker run -d --name laboratorio-final -p 80:3000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/laboratorio-final:prueba

  DAST:
    needs: Despliegue
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar análisis DAST con OWASP ZAP
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py \
            -t http://${{ 0.tcp.ngrok.io }} \
            -r zap-report.html || true

      - name: Subir reporte ZAP como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html